export const CONTACT_TYPES = {
    CREATE_CONTACT: 'createContact',
    SELECT_CONTACT: 'selectContact',

    // Action
    POST_CONTACT_ACTION: 'POST_CONTACT_ACTION',
    PUT_CONTACT_ACTION: 'PUT_CONTACT_ACTION',
    GET_CONTACTS_ACTION: 'GET_CONTACTS_ACTION',
    DELETE_CONTACT_ACTION: 'DELETE_CONTACT_ACTION',
    // Request
    POST_CONTACT_REQUEST: 'POST_CONTACT_REQUEST',
    PUT_CONTACT_REQUEST: 'PUT_CONTACT_REQUEST',
    GET_CONTACTS_REQUEST: 'GET_CONTACTS_REQUEST',
    DELETE_CONTACT_REQUEST: 'DELETE_CONTACT_REQUEST',
    // Success
    POST_CONTACT_SUCCESS: 'POST_CONTACT_SUCCESS',
    PUT_CONTACT_SUCCESS: 'PUT_CONTACT_SUCCESS',
    GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
    DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
    // Error
    POST_CONTACT_ERROR: 'POST_CONTACT_ERROR',
    PUT_CONTACT_ERROR: 'PUT_CONTACT_ERROR',
    GET_CONTACTS_ERROR: 'GET_CONTACTS_ERROR',
    DELETE_CONTACT_ERROR: 'DELETE_CONTACT_ERROR'
}