export const CONTACT_TYPES = {
    CREATE_CONTACT: 'createContact',
    SELECT_CONTACT: 'selectContact',

    // Action
    ADD_NEW_CONTACT_ACTION: 'ADD_NEW_CONTACT_ACTION',
    UPDATE_CONTACT_ACTION: 'UPDATE_CONTACT_ACTION',
    GET_CONTACTS_ACTION: 'GET_CONTACTS_ACTION',
    DELETE_CONTACT_ACTION: 'DELETE_CONTACT_ACTION',
    // Request
    ADD_NEW_CONTACT_REQUEST: 'ADD_NEW_CONTACT_REQUEST',
    UPDATE_CONTACT_REQUEST: 'UPDATE_CONTACT_REQUEST',
    GET_CONTACTS_REQUEST: 'GET_CONTACTS_REQUEST',
    DELETE_CONTACT_REQUEST: 'DELETE_CONTACT_REQUEST',
    // Success
    ADD_NEW_CONTACT_SUCCESS: 'ADD_NEW_CONTACT_SUCCESS',
    UPDATE_CONTACT_SUCCESS: 'UPDATE_CONTACT_SUCCESS',
    GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
    DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_RSUCCESS',
    // Error
    ADD_NEW_CONTACT_ERROR: 'ADD_NEW_CONTACT_ERROR',
    UPDATE_CONTACT_ERROR: 'UPDATE_CONTACT_ERROR',
    GET_CONTACTS_ERROR: 'GET_CONTACTS_ERROR',
    DELETE_CONTACT_ERROR: 'DELETE_CONTACT_ERROR'
}